import 'package:flutter/material.dart';

final List<String> categories = [
  'Dev Calculator',
  'Algebra',
  'Geometry',
  'Unit Converters',
  'Finance',
  'Health',
  'Data & Time',
  'Physics',
  'Chemistry',
  'Cooking',
];

final Map<String, List<String>> subcategoryMap = {
  'Dev Calculator': [
    'Data Conversion',
    'Base64 Converter',
    'JsonMate',
    'Color Code Converter',
  ],
  'Algebra': [
    'Percentage',
    'Average',
    'Proportion',
    'Ratio',
    'Equations',
    'Fractions',
  ],
  'Geometry': ['Shape', 'Body'],
  'Unit Converters': [
    'Length',
    'Weight',
    'Temperature',
    'Acceleration',
    'Area',
    'Data Storage',
    'Time Conversion',
  ],
  'Finance': [
    'Interest',
    'Loan',
    'Discount',
    'Sales Tax',
    'Tip',
    'Unit Price',
    'Profit Margin',
  ],
  'Health': ['BMI' /*, 'Calorie Burn', 'Body fat'*/],
  'Data & Time': ['Age Calculator', 'Time Interval', 'Add & Subtract'],
  'Physics': ['Motion', 'Force', 'Energy'],
  'Chemistry': ['Moles', 'Atoms', 'Periodic Table'],
  'Cooking': ['Temperature (Cooking)', 'Weight (Cooking)', 'Volume', 'Cooking'],
};

final Map<String, String> categoryIcons = {
  'Dev Calculator': '💻',
  'Algebra': '🧮',
  'Geometry': '📐',
  'Unit Converters': '♾️',
  'Finance': '💵',
  'Health': '🏥',
  'Data & Time': '⏲️',
  'Physics': '⚛️',
  'Chemistry': '🧪',
  'Cooking': '🍴',
};

final Map<String, String> subcategoryIcons = {
  'Percentage': '📊',
  'Average': '📈',
  'Proportion': '🔢',
  'Shape': '📐',
  'Length': '📏',
  'Weight': '⚖️',
  'Temperature': '🌡️',
  'Interest': '💰',
  'Loan': '🏦',
  'Discount': '🏷️',
  'Sales Tax': '🧾',
  'Tip': '🙌',
  'Unit Price': '⚖️',
  'Profit Margin': '📈',
  'BMI': '⚕️',
  'Calorie Burn': '🔥',
  'Date Converter': '📆',
  'Time Zone Converter': '🌍',
  'Motion': '🏃',
  'Force': '💪',
  'Energy': '⚡',
  'Moles': '🧪',
  'Atoms': '🔬',
  'Periodic Table': '📜',
  'Temperature (Cooking)': '🌡️',
  'Weight (Cooking)': '⚖️',
  'Volume': '🥛',
  'Age Calculator': '🎂',
  'Time Interval': '⌚',
  'add & subtract': '⌛',
  'Ratio': '⚖️',
  'Equations': '∑',
  'Fractions': '🍰',
  'Area': '🧱',
  'Shape': '🔷',
  'Volume': '🧊',
  'Body': '🔲',
  'Data Conversion': '🔢',
  'Base64 Converter': '📦',
  'JsonMate': '🧰',
  'Color Code Converter': '🎨',
  'Acceleration': '🚗',
  'Data Storage': '💽',
  'Time Conversion': '⌚',
  'Add & Subtract': '➕➖',
};

final buttonLabels = [
  ['C', 'tan', 'sin', 'cos'],
  ['(', ')', '√', '!'],
  ['7', '8', '9', '/'],
  ['4', '5', '6', '*'],
  ['1', '2', '3', '-'],
  ['.', '0', '=', '+'],
];

final Map<String, Color> categoryColors = {
  'Algebra': Colors.indigo,
  'Geometry': Colors.teal,
  'Unit Converters': Colors.deepPurple,
  'Finance': Colors.green,
  'Health': Colors.redAccent,
  'Data & Time': Colors.orange,
  'Physics': Colors.blueGrey,
  'Chemistry': Colors.amber,
  'Cooking': Colors.brown,
  'Dev Calculator': Colors.cyan,
};

final Map<String, Color> subcategoryColors = {
  'Percentage': Colors.indigo,
  'Average': Colors.indigoAccent,
  'Proportion': Colors.deepPurple,
  'Shape': Colors.teal,
  'Length': Colors.deepPurpleAccent,
  'Weight': Colors.purple,
  'Temperature': Colors.red,
  'Interest': Colors.green,
  'Loan': Colors.greenAccent,
  'Discount': Colors.deepOrange,
  'Sales Tax': Colors.teal,
  'Tip': Colors.pinkAccent,
  'Unit Price': Colors.indigo,
  'Profit Margin': Colors.lightGreen,
  'BMI': Colors.redAccent,
  'Calorie Burn': Colors.deepOrange,
  'Date Converter': Colors.orange,
  'Time Zone Converter': Colors.deepOrangeAccent,
  'Motion': Colors.blueGrey,
  'Force': Colors.blue,
  'Energy': Colors.lightBlue,
  'Moles': Colors.amber,
  'Atoms': Colors.amberAccent,
  'Periodic Table': Colors.yellow,
  'Temperature (Cooking)': Colors.red,
  'Weight (Cooking)': Colors.brown,
  'Volume': Colors.brown.shade300,
  'Data Conversion': Colors.teal,
  'Base64 Converter': Colors.green,
  'JsonMate': Colors.lightBlue,
  'Color Code Converter': Colors.yellow,
};
